//
// Generated file, do not edit! Created by nedtool 5.5 from ack.msg.
//

#ifndef __ACK_M_H
#define __ACK_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0505
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>ack.msg:1</tt> by nedtool.
 * <pre>
 * message ackMessage
 * {
 * }
 * </pre>
 */
class ackMessage : public ::omnetpp::cMessage
{
  protected:

  private:
    void copy(const ackMessage& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const ackMessage&);

  public:
    ackMessage(const char *name=nullptr, short kind=0);
    ackMessage(const ackMessage& other);
    virtual ~ackMessage();
    ackMessage& operator=(const ackMessage& other);
    virtual ackMessage *dup() const override {return new ackMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const ackMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, ackMessage& obj) {obj.parsimUnpack(b);}


#endif // ifndef __ACK_M_H

