//
// Generated file, do not edit! Created by nedtool 5.5 from layer.msg.
//

#ifndef __LAYER_M_H
#define __LAYER_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0505
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>layer.msg:1</tt> by nedtool.
 * <pre>
 * message layerMessage
 * {
 *     int layer;
 *     simtime_t timeFrame;
 * }
 * </pre>
 */
class layerMessage : public ::omnetpp::cMessage
{
  protected:
    int layer;
    ::omnetpp::simtime_t timeFrame;

  private:
    void copy(const layerMessage& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const layerMessage&);

  public:
    layerMessage(const char *name=nullptr, short kind=0);
    layerMessage(const layerMessage& other);
    virtual ~layerMessage();
    layerMessage& operator=(const layerMessage& other);
    virtual layerMessage *dup() const override {return new layerMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getLayer() const;
    virtual void setLayer(int layer);
    virtual ::omnetpp::simtime_t getTimeFrame() const;
    virtual void setTimeFrame(::omnetpp::simtime_t timeFrame);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const layerMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, layerMessage& obj) {obj.parsimUnpack(b);}


#endif // ifndef __LAYER_M_H

